// Code generated by "enumer -type=PluginRuntimeType -trimprefix=PluginRuntimeType -transform=snake"; DO NOT EDIT.

package consts

import (
	"fmt"
	"strings"
)

const _PluginRuntimeTypeName = "unsupportedcontainer"

var _PluginRuntimeTypeIndex = [...]uint8{0, 11, 20}

const _PluginRuntimeTypeLowerName = "unsupportedcontainer"

func (i PluginRuntimeType) String() string {
	i -= 1
	if i >= PluginRuntimeType(len(_PluginRuntimeTypeIndex)-1) {
		return fmt.Sprintf("PluginRuntimeType(%d)", i+1)
	}
	return _PluginRuntimeTypeName[_PluginRuntimeTypeIndex[i]:_PluginRuntimeTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PluginRuntimeTypeNoOp() {
	var x [1]struct{}
	_ = x[PluginRuntimeTypeUnsupported-(1)]
	_ = x[PluginRuntimeTypeContainer-(2)]
}

var _PluginRuntimeTypeValues = []PluginRuntimeType{PluginRuntimeTypeUnsupported, PluginRuntimeTypeContainer}

var _PluginRuntimeTypeNameToValueMap = map[string]PluginRuntimeType{
	_PluginRuntimeTypeName[0:11]:       PluginRuntimeTypeUnsupported,
	_PluginRuntimeTypeLowerName[0:11]:  PluginRuntimeTypeUnsupported,
	_PluginRuntimeTypeName[11:20]:      PluginRuntimeTypeContainer,
	_PluginRuntimeTypeLowerName[11:20]: PluginRuntimeTypeContainer,
}

var _PluginRuntimeTypeNames = []string{
	_PluginRuntimeTypeName[0:11],
	_PluginRuntimeTypeName[11:20],
}

// PluginRuntimeTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PluginRuntimeTypeString(s string) (PluginRuntimeType, error) {
	if val, ok := _PluginRuntimeTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PluginRuntimeTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PluginRuntimeType values", s)
}

// PluginRuntimeTypeValues returns all values of the enum
func PluginRuntimeTypeValues() []PluginRuntimeType {
	return _PluginRuntimeTypeValues
}

// PluginRuntimeTypeStrings returns a slice of all String values of the enum
func PluginRuntimeTypeStrings() []string {
	strs := make([]string, len(_PluginRuntimeTypeNames))
	copy(strs, _PluginRuntimeTypeNames)
	return strs
}

// IsAPluginRuntimeType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PluginRuntimeType) IsAPluginRuntimeType() bool {
	for _, v := range _PluginRuntimeTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
