// Code generated by "enumer -type=MountMigrationStatus -trimprefix=MigrationStatus -transform=kebab"; DO NOT EDIT.

package vault

import (
	"fmt"
	"strings"
)

const _MountMigrationStatusName = "in-progresssuccessfailure"

var _MountMigrationStatusIndex = [...]uint8{0, 11, 18, 25}

const _MountMigrationStatusLowerName = "in-progresssuccessfailure"

func (i MountMigrationStatus) String() string {
	if i < 0 || i >= MountMigrationStatus(len(_MountMigrationStatusIndex)-1) {
		return fmt.Sprintf("MountMigrationStatus(%d)", i)
	}
	return _MountMigrationStatusName[_MountMigrationStatusIndex[i]:_MountMigrationStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MountMigrationStatusNoOp() {
	var x [1]struct{}
	_ = x[MigrationStatusInProgress-(0)]
	_ = x[MigrationStatusSuccess-(1)]
	_ = x[MigrationStatusFailure-(2)]
}

var _MountMigrationStatusValues = []MountMigrationStatus{MigrationStatusInProgress, MigrationStatusSuccess, MigrationStatusFailure}

var _MountMigrationStatusNameToValueMap = map[string]MountMigrationStatus{
	_MountMigrationStatusName[0:11]:       MigrationStatusInProgress,
	_MountMigrationStatusLowerName[0:11]:  MigrationStatusInProgress,
	_MountMigrationStatusName[11:18]:      MigrationStatusSuccess,
	_MountMigrationStatusLowerName[11:18]: MigrationStatusSuccess,
	_MountMigrationStatusName[18:25]:      MigrationStatusFailure,
	_MountMigrationStatusLowerName[18:25]: MigrationStatusFailure,
}

var _MountMigrationStatusNames = []string{
	_MountMigrationStatusName[0:11],
	_MountMigrationStatusName[11:18],
	_MountMigrationStatusName[18:25],
}

// MountMigrationStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MountMigrationStatusString(s string) (MountMigrationStatus, error) {
	if val, ok := _MountMigrationStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MountMigrationStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MountMigrationStatus values", s)
}

// MountMigrationStatusValues returns all values of the enum
func MountMigrationStatusValues() []MountMigrationStatus {
	return _MountMigrationStatusValues
}

// MountMigrationStatusStrings returns a slice of all String values of the enum
func MountMigrationStatusStrings() []string {
	strs := make([]string, len(_MountMigrationStatusNames))
	copy(strs, _MountMigrationStatusNames)
	return strs
}

// IsAMountMigrationStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MountMigrationStatus) IsAMountMigrationStatus() bool {
	for _, v := range _MountMigrationStatusValues {
		if i == v {
			return true
		}
	}
	return false
}
